### ISSUE TITLE
HA/Migration Issues to be fixed.

### ISSUE THREAD

**Issue by unakatsuo** [axsh/wakame-vdc#464]
- [ ] HA evacuation: missing considerations for some instance states:
     halted, pending
- [x] `ha_enabled` flags is ignored. #479 
- [x]  `vdc-manage modify host/storage` overwrites unset parameters. #469,  #474 
- [ ] Can not terminate the instance with: state=halted, status=online.
- [x] `host_node.schduling_enabled` flag goes back to false by hma after modifying by `vdc-manage host modify --scheduling-enabled=true`
- [x] `vdc-manage host add/modify` should accept 0 value for options. It is needed for HA overcapacity test scenario: #476
  --cpu-cores, --memory-size, --disk-space
- [x] hma.conf: op_and operator is not working. axsh/wakame-vdc#484
- [x] hva fails at instance migration because it builds -incoming option parameter wrongly. #473 
- [x] halted instance becomes running state after HA event. https://github.com/axsh/wakame-vdc/pull/491
